apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: cats-dogs-api-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: cats-dogs-api
  endpoints:
  - port: 8080
    path: /metrics
    interval: 30s
